import { NextRequest, NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/service";
import { getCardProject } from "@/lib/supabase/queries/card-projects";
import { createCardDraft } from "@/lib/supabase/queries/card-drafts";
import {
  ClaudeGatewayError,
  generateJsonWithClaude,
  getActiveModel,
} from "@/lib/ai/claude-client";
import { getJeJalPromptPack, getNegativePromptBlock } from "@/lib/config/prompt-pack";
import { getLearnedCopyPatterns } from "@/lib/supabase/queries/learning";
import { isStoryDraft, StoryDraft, StoryCard } from "@/lib/ai/types";

const SYSTEM_PROMPT = `You are the JeJal Card Factory story generator.
You produce structured card stories for the JeJal Instagram brand.
You follow the rules in the prompt pack EXACTLY — no improvisation.
You respond with valid JSON only. No markdown, no prose, no explanation.`;

function buildUserPrompt({
  title,
  topic,
  content_type,
  card_count,
  extra_instruction,
  promptPack,
}: {
  title: string;
  topic: string;
  content_type: string;
  card_count: number;
  extra_instruction: string;
  promptPack: string;
}): string {
  return `
${promptPack}

---

## YOUR TASK

Generate a JeJal card story with EXACTLY ${card_count} cards.

Project details:
- Title: ${title}
- Topic: ${topic}
- Content type / Story schema: ${content_type}
${extra_instruction ? `- Extra instruction: ${extra_instruction}` : ""}

Output a single JSON object that exactly matches this structure:
{
  "title": "<project title>",
  "topic": "<topic summary>",
  "content_type": "${content_type}",
  "cards": [
    {
      "card_number": 1,
      "role": "<story role, e.g. cover/hook/escalation/punchline/closing>",
      "top_text": "<German copy, 1–2 short lines max, casual student tone>",
      "character_action": "<JeJal pose name from the allowed poses table>",
      "character_emotion": "<JeJal emotion name from the allowed emotions table>",
      "image_prompt": "<VARIABLE PARTS ONLY: 2-4 lines — Pose, Expression (eyes), Prop (optional), Direction>"
    }
  ]
}

Rules:
- top_text: German only, 1–2 lines, max ~12 words per line, casual student tone, no hashtags.
- card 1 must be the Cover with POV: text in the center and character peeking from bottom-right.
- last card must be the Closing card (fixed JeJal logo, no top_text needed — write "Closing card" for top_text).
- character_action and character_emotion must use the exact names from the reference tables.
- image_prompt: VARIABLE PARTS ONLY (pose, expression, prop, direction). 2-4 lines. NO Lock Block header.
- Do NOT include negative_prompt — the server fills it in automatically.
- Return ONLY the JSON. No prose before or after.
`.trim();
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  let body: {
    card_count?: number;
    content_type?: string;
    extra_instruction?: string;
  } = {};
  try {
    body = await request.json();
  } catch {
    // use defaults
  }

  const card_count = Math.min(7, Math.max(5, Number(body.card_count) || 5));
  const extra_instruction = body.extra_instruction ?? "";

  try {
    const db = createServiceClient();

    // Load project
    const project = await getCardProject(db, id);
    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const content_type = body.content_type ?? project.content_type;

    // Load learned patterns from past approved projects (best-effort)
    let learnedPatterns: string | undefined;
    try {
      learnedPatterns = await getLearnedCopyPatterns(db) || undefined;
    } catch {
      // non-critical
    }

    // Build prompt
    const promptPack = getJeJalPromptPack(learnedPatterns);
    const userPrompt = buildUserPrompt({
      title: project.title,
      topic: project.topic,
      content_type,
      card_count,
      extra_instruction,
      promptPack,
    });

    // Call Claude
    const parsed = await generateJsonWithClaude({
      systemPrompt: SYSTEM_PROMPT,
      userPrompt,
      schemaName: "StoryDraft",
      maxTokens: 4096,
    });

    if (!isStoryDraft(parsed)) {
      return NextResponse.json(
        {
          error: "Claude returned an unexpected shape",
          raw: parsed,
        },
        { status: 502 }
      );
    }

    // Fill in negative_prompt server-side (not generated by Claude to save tokens)
    const negativePrompt = getNegativePromptBlock();
    const story = parsed as StoryDraft;
    story.cards = story.cards.map((card: StoryCard) => ({
      ...card,
      negative_prompt: card.negative_prompt ?? negativePrompt,
    }));

    // Save to card_drafts
    const model = getActiveModel();
    const draft = await createCardDraft(db, {
      project_id: id,
      cards_json: parsed as unknown as import("@/lib/supabase/types").Json,
      source_docs: ["story_schema", "content_rules", "copywriting_rules", "character_bible", "example_library"],
      generation_prompt: userPrompt.slice(0, 2000), // truncate for storage
      model,
    });

    return NextResponse.json({ draft_id: draft.id, story: parsed }, { status: 201 });
  } catch (err) {
    if (err instanceof ClaudeGatewayError) {
      console.error("Claude gateway error while generating story", {
        status: err.status,
        body: err.body.slice(0, 2000),
      });

      return NextResponse.json(
        {
          error:
            "Claude 게이트웨이가 일시적으로 응답하지 않습니다. 잠시 후 다시 생성해 주세요.",
          detail: `Upstream returned ${err.status}`,
        },
        { status: 502 }
      );
    }

    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
